services:
  postgres:
    container_name: test_shop_postgres_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - test_shop_net
    restart: unless-stopped

  pgadmin:
    container_name: test_shop_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - test_shop_net
    restart: unless-stopped

  mongo:
    container_name: test_shop_mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo:/data
    ports:
      - "27017:27017"
    networks:
      - test_shop_net
    restart: unless-stopped

  mongo_express:
    container_name: test_shop_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_AUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "8081:8081"
    networks:
      - test_shop_net
    depends_on:
      - mongo
    restart: unless-stopped


networks:
  test_shop_net:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mongo:
